defaults:
  - baseline
  - _self_

k_fold: 0

writer:
  _target_: src.logger.comet_writer.CometMLWriter
  project_name: "triplexnet"
  experiment_name: "triplexnet_grummit"
  run_name: "grummit_triplexnetv2"
  api_key: null
  workspace: null
  mode: "online"
  loss_names:
    - "loss"
