defaults:
  - grummit_triplexnet
  - _self_

split_method: genomic_bin_representative

target_class_ratio: 4.0

rep_split_n_quantiles: 4
rep_split_min_stratum_count: 3

trainer:
  threshold_tuning_during_training: false

writer:
  run_name: "grummit_triplexnet_reprsplit"
